version: "3.2"
services:
  api:
    image: public.ecr.aws/w4d8o1l0/taxi-api:latest
    container_name: taxi_api
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - redis
      - model
    ports:
      - "8000:5000"
    networks:
      - shared_network

  redis:
    image: redis:6.2.6
    container_name: redis
    networks:
      - shared_network

  model:
    image: public.ecr.aws/w4d8o1l0/taxi-ml-service:latest
    container_name: taxi_ml_service
    depends_on:
      - redis
    networks:
      - shared_network

  ui:
    image: public.ecr.aws/w4d8o1l0/taxi-ui:latest
    container_name: taxi_ui
    environment:
      API_HOST: $API_HOST
    ports:
      - "9090:9090"
    networks:
      - shared_network

  populate-db:
    image: public.ecr.aws/w4d8o1l0/populate-db:latest
    container_name: populate_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    networks:
      - shared_network  

networks:
  shared_network:
    external: true